name: actions
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest

    steps:
      - name: simple js action
        id: greet
        run: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: satya
      - name: output time
        run : echo "${{ steps.greet.outputs.time }}"

