name: Checkout
on: [push]

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run : ls -al 
      - uses: actions/checkout@v3
      - name: after action 
        run : ls -al   
  checkout-and-display-file:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -a 
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main 
      - name: list files agter
        run : ls -al 
      

