name: Repository Events
on: 
  push:
  pull_request:
    types: [opened, assigned,reopened, synchronize]
  issues:
    types: [opened, edited, closed]

jobs:
  event_checkout:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
