name: First-workflow
on: [push]


jobs:
  run-shell-commandsw:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo " hello world"
      - name: multiple commands
        run : |
          node -v
          npm -v  
