name: workingdirs and shells
on : [push]
defaults:
  run:
    shell: bash
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
      - name: Display file systems 
        run : |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: cjhjange the workig dir
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display file systems 
        run : |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name : pytho shell
        shell: python
        run: |
          import platform
          print(platform.processor())
